server:
    port: 3171
    servlet:
        context-path: /api
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/db_kkuil_api
        username: ENC(kD23HRasvx0l/GeauMQo5/KVy4GTA5VCQVJp2gipPCbOV8h0wTwXEpSnH4249xGv)
        password: ENC(cz5o9HHM4d+3eARfoZfrzq6NyPnboAPjH5d7gk3ZidFKZxF3NN9iYokgUK5h1fxa)
    data:
        # redis
        redis:
            database: 0
            host: localhost
            port: 6379
            password: ENC(88OxONO6Wkz/MXTHFHSDZw3VFXTzCa14gceP3veAD7P0r9hr7Vdpb6Nos925AHn+)
# springdoc-openapi项目配置
springdoc:
    swagger-ui:
        path: /swagger-ui.html
        tags-sorter: alpha
        operations-sorter: alpha
    api-docs:
        path: /v3/api-docs
        enabled: on
    group-configs:
        -   group: 'default'
            paths-to-match: '/**'
            packages-to-scan: com.kkuil.kkuilapiinterface.controller
    packages-to-scan: com.kkuil.kkuilapiinterface.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
    enable: true
    setting:
        language: zh_cn
logging:
    level:
        web: debug
invoke-count:
    base-url: http://127.0.0.1:3170
    location: /api/interface/invoke-count