server:
    port: 3170
    servlet:
        context-path: /api
mybatis-plus:
    configuration:
        map-underscore-to-camel-case: false
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.kkuil.api.model.po
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/db_kkuil_api
        username: ENC(kD23HRasvx0l/GeauMQo5/KVy4GTA5VCQVJp2gipPCbOV8h0wTwXEpSnH4249xGv)
        password: ENC(cz5o9HHM4d+3eARfoZfrzq6NyPnboAPjH5d7gk3ZidFKZxF3NN9iYokgUK5h1fxa)
