server:
    port: 3172
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/db_kkuil_api
        username: ENC(kD23HRasvx0l/GeauMQo5/KVy4GTA5VCQVJp2gipPCbOV8h0wTwXEpSnH4249xGv)
        password: ENC(cz5o9HHM4d+3eARfoZfrzq6NyPnboAPjH5d7gk3ZidFKZxF3NN9iYokgUK5h1fxa)
    data:
        # redis
        redis:
            database: 0
            host: localhost
            port: 6379
            password: ENC(88OxONO6Wkz/MXTHFHSDZw3VFXTzCa14gceP3veAD7P0r9hr7Vdpb6Nos925AHn+)
    main:
        web-application-type: reactive
    cloud:
        gateway:
            routes:
                -   id: api-interface
                    uri: http://127.0.0.1:3171
                    predicates:
                        - Path=/api/**
                    filters:
                        - AddRequestHeader=X-Request-Flag, 0abf1e51-9ccc-4cbc-93b0-d2b9ac6e575e
                        -   name: RequestRateLimiter
                            args:
                                redis-rate-limiter.replenishRate: 10
                                redis-rate-limiter.burstCapacity: 20
                                redis-rate-limiter.requestedTokens: 1
                                keyResolver: "#{@uriKeyResolver}"